# Generated by Django 5.1.1 on 2024-09-17 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='route_name',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='stop_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_id',
            field=models.CharField(default='default_bus_id', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(default='Unknown Bus', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='stops',
            field=models.ManyToManyField(related_name='buses', to='seat.stop'),
        ),
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(default='default_stop_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seat.bus'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('available', 'Available')], default='available', max_length=10),
        ),
    ]
