# Generated by Django 5.1.1 on 2024-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_remove_bus_bus_number_remove_bus_route_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(default='Unknown Stop', max_length=100),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(default='default_stop_id', max_length=100, unique=True),
        ),
    ]
