# Generated by Django 5.1.1 on 2024-09-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_alter_seat_seat_number_alter_stop_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='bus',
        ),
    ]
