# Generated by Django 5.1.1 on 2024-09-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0004_remove_seat_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seat.bus'),
            preserve_default=False,
        ),
    ]
