# Generated by Django 5.0.3 on 2024-09-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_stop_remove_bus_route_remove_seat_is_occupied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='stops',
            field=models.ManyToManyField(related_name='buses', to='seat.stop'),
        ),
        migrations.AddField(
            model_name='seat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
